name: Python application PRs

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'eol-release/*'

jobs:
  test:
    uses: eol-uchile/workflow-commons/.github/workflows/pythonapp_external.yml@pythonapp-2
    with:
      environment: external-pull-request
      django-lms: true
      django-cms: false
