name: Python application

on:
  push:
    branches:
      - 'eol/koa'
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'eol/koa'

jobs:
  test:
    uses: eol-uchile/workflow-commons/.github/workflows/pythonapp.yml@vastorga/environment
    with:
      environment: 'cmmedu' 
      app_id: ${{ vars.EOLITO_BOT_APP_ID }}
      django-lms: true
      django-cms: false
      platform-eol: true
      platform-openuchile: true
    secrets:
      private_key: ${{ secrets.EOLITO_BOT_PRIVATE_KEY }}
